name: skein_rest_dio_client
description: An implementation of the skein_rest_client based on the dio package.
version: 0.0.10
homepage: https://github.com/skein-dart/skein_rest_dio_client

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  skein_rest_client:
#    path: ../skein_rest_client
    git:
      url: https://github.com/skein-dart/skein_rest_client.git
      ref: 0.0.10
  dio: ^4.0.4
  async: ^2.8.2
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
  mockito: ^5.0.17
  build_runner: ^2.1.2
  equatable:
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
